//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastVerCode.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastVerCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;yzm_id&quot;
        ///
        ///[验证码id]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;key&quot;
        ///
        ///+8z1lB53mIowlCmwh
        ///-----------------------------7dd3901221176-- 的本地化字符串。
        /// </summary>
        internal static string getErrorCode {
            get {
                return ResourceManager.GetString("getErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;yzm_id&quot;
        ///
        ///[打码Id]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;key&quot;
        ///
        ///XTKH8Uyb9f6IfTKH4
        ///-----------------------------7dd3901221176-- 的本地化字符串。
        /// </summary>
        internal static string getResultParameter {
            get {
                return ResourceManager.GetString("getResultParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;user_name&quot;
        ///
        ///[username]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;user_pw&quot;
        ///
        ///[password]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;upload&quot;; filename=&quot;ab497e47984c60d9bbc93d5b920e036c.jpg&quot;
        ///Content-Type: image/gif 的本地化字符串。
        /// </summary>
        internal static string getUpload1 {
            get {
                return ResourceManager.GetString("getUpload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;yzmtype_mark&quot;
        ///
        ///[yzmtype]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;yzm_minlen&quot;
        ///
        ///[yzm_minlen]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;yzm_maxlen&quot;
        ///
        ///[yzm_maxlen]
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd165a60630
        ///Content-Disposition: form-data; n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string getUpload2 {
            get {
                return ResourceManager.GetString("getUpload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_name&quot;
        ///
        ///[username]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_pw&quot;
        ///
        ///[password]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;key&quot;
        ///
        ///kldHJgXoLnMa3gXUF
        ///-----------------------------7dd3901221176-- 的本地化字符串。
        /// </summary>
        internal static string getUser {
            get {
                return ResourceManager.GetString("getUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_name&quot;
        ///
        ///[username]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_pw&quot;
        ///
        ///[password]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;mac&quot;
        ///
        ///MDA1MDU2YzAwMDAx
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;key&quot;
        ///
        ///kldHJgXoLnMa3gXUF
        ///-----------------------------7dd3901221176-- 的本地化字符串。
        /// </summary>
        internal static string getUserCode {
            get {
                return ResourceManager.GetString("getUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_name&quot;
        ///
        ///[username]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_pw&quot;
        ///
        ///[password]
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_email&quot;
        ///
        ///
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_qq&quot;
        ///
        ///
        ///-----------------------------7dd3901221176
        ///Content-Disposition: form-data; name=&quot;user_phone&quot;
        ///
        ///
        ///---- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Reglz {
            get {
                return ResourceManager.GetString("Reglz", resourceCulture);
            }
        }
    }
}
